version: '3'

services: 

  nginx:
    image: emunari/desafio-docker-nginx:latest
    container_name: nginx
    networks: 
      - nodenet
    ports: 
      - "8080:80"
    depends_on:
      - app

  app:
    image: emunari/desafio-docker-node:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh 
    command: node index.js
    networks: 
      - nodenet
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks: 
  nodenet:
    driver: bridge      